### ISSUE TITLE
Thoughts about the repo's name

### ISSUE THREAD

**Issue by simonepri** [keymetrics/docker-pm2#25]
@Unitech what do you think about changing the repo's name from `pm2-docker-alpine` to  just `pm2-docker`
and then add support for more docker images?

**Comment by Unitech** [comment]
A rewording make sense. What do you mean by adding support for more docker images?

**Comment by simonepri** [comment]
Github should handle the url redirect automagically, but i'm not sure about that.
Maybe a new repo is better, but I think it can generate confusion.

**Comment by simonepri** [comment]
The official nodeJS Docker repo ships more than just alpine's node images.
https://hub.docker.com/r/library/node/tags/

**Comment by simonepri** [comment]
Maybe we can create a script that pulls automatically all tags from the Official nodeJS docker repo and generates all Dockerfile for this repo.

**Comment by simonepri** [comment]
This could be the first step, and then we will think about implications of the rewording.

**Comment by Unitech** [comment]
Alright I see, thanks. Building that script would be a great idea, let me know if you need any help on that.
I confirm that github handle well redirection when renaming a repo, anyway I will impact this change on the docker registry

**Comment by simonepri** [comment]
`pm2-docker` or `docker-pm2` ??
The official node repo is called:
`docker-node`

I'll try to do the script and then I'll open a PR 🚀

**Comment by vmarchaud** [comment]
+1 for `docker-pm2`

**Comment by Unitech** [comment]
Let's go for docker-pm2!

**Comment by simonepri** [comment]
The only problem is that currently the binary is called `pm2-docker`. We should also rename the binary into the pm2 repo:
https://github.com/Unitech/pm2/search?utf8=%E2%9C%93&q=pm2-docker

**Comment by vmarchaud** [comment]
@simonepri I don't think it's that much a problem, there is a difference between the binary name and the image name

**Comment by Unitech** [comment]
Hello @simonepri!
So what should we do about the repo name on the docker registry? Do we rename pm2-docker-alpine to docker-pm2 or I create a second container image named docker-pm2?

**Comment by simonepri** [comment]
I think the best way is to keep `pm2-docker-alpine`, since we cannot break users' images and create a new image named just `pm2`
But I think we could wait until I end the script.

**Comment by Unitech** [comment]
I thought we would create a new image called docker-pm2, but pm2 as an image name would be nice also, why not.
Looking forward this script, that would be great to auto build this container based on the node image

**Comment by Unitech** [comment]
@simonepri what do you think of https://hub.docker.com/r/keymetrics/docker-pm2/? It's a replicat of pm2-docker-alpine but at least it has the right name

**Comment by simonepri** [comment]
It makes sense. Why did you choose docker-pm2 instead of just pm2?
Sorry for the delay but I was full of work. I will try to improve the image asap.

**Comment by Unitech** [comment]
let's keep it short https://hub.docker.com/r/keymetrics/pm2/

**Comment by simonepri** [comment]
Wonderful can you add me as collaborator?
I want to see if its possible to use this:
https://docs.docker.com/docker-hub/builds/#repository-links
This will solve our sync problem with the official nodejs image.

**Comment by Unitech** [comment]
that sounds good, I've just added you as a collaborator

**Comment by simonepri** [comment]
Thanks @Unitech but I can't see any difference:
![image](https://user-images.githubusercontent.com/3505087/29004140-4752a396-7ac3-11e7-88b2-f4144a793456.png)

**Comment by Unitech** [comment]
I've double checked, you've been added to the repo:

![image](https://user-images.githubusercontent.com/757747/29007132-300e949e-7afd-11e7-8fcd-a143713dfbe9.png)

**Comment by simonepri** [comment]
It seems that on the Docker Hub a _Collaborator_ is just someone that can see the image also if that is set as private:
https://docs.docker.com/docker-hub/repos/#collaborators-and-their-role

**Comment by Unitech** [comment]
I've followed [this tutorial](https://success.docker.com/Cloud/Solve/How_do_I_convert_my_Docker_Hub%2F%2FCloud_user_account_into_an_organization_account%3F) to turn keymetrics into an organization and I've added you as owner :)

**Comment by simonepri** [comment]
@Unitech thanks.
Those are the things we have to do:
- [x] Link the `node`'s repo to the `pm2`'s repo on the `Docker Hub`.<br>*This will trigger the build of pm2's images each time node's images are built.*
- [x] Create a `trigger` in the build settings of the `pm2`'s  repo on the `Docker Hub`.<br>*This will generates a link that when POSTed will trigger the build of pm2's images.*
- [ ] Add that `trigger` in the `Web Hook` section of the `pm2` repo on `npm`.<br>*Each time a new version of pm2 is released on npm our pm2 repo on Docker Hub will be rebuilt.*

More info about the last step can be found here:
http://blog.npmjs.org/post/145260155635/introducing-hooks-get-notifications-of-npm

**Comment by simonepri** [comment]
`Hooks` on `npm` seems to be a paid feature. 
Instead we can add the `trigger` directly in the `Web Hooks` section of `pm2`'s `GitHub` repo.

**Comment by Unitech** [comment]
Awesome! Should we export all the tags from the official node repo also?

- deprecation notice https://hub.docker.com/r/keymetrics/pm2-docker-alpine/
- on new pm2 release, trigger auto build 

![image](https://user-images.githubusercontent.com/757747/29343031-becb48d4-822e-11e7-9a6e-596dc3a4756b.png)

Also I've built something that may interest you: https://github.com/Unitech/pm2/issues/3094 feedbacks welcome!

**Comment by simonepri** [comment]
Also we should look how to mark that image as `official`.
`PM2` is quite huge project, I think that the Docker team will publish it without any particular concern.
https://docs.docker.com/docker-hub/official_repos/

**Comment by Unitech** [comment]
I've replaced all occurences of pm2-docker-alpine to pm2
To export all tags, do we need to create a folder for each tag?

**Comment by vmarchaud** [comment]
@simonepri Node 7 has been [dropped](https://github.com/docker-library/official-images/pull/3349) of the official node image repo, also pm2 doesn't support node 7 since it isnt a LTS. We should not build image on it i think
