### ISSUE TITLE
How can I run the container follow the Usage Guide

### ISSUE THREAD

**Issue by axetroy** [keymetrics/docker-pm2#30]
1. Create a Dockerfile in your Node.js app project
2. Create a pm2.json in your Node.js app project
3. Build and Run your image

```bash
$ docker build -t your-app-name .

Sending build context to Docker daemon 51.42 MB
Step 1 : FROM keymetrics/pm2-docker-alpine:latest
 ---> fea23810c91d
Step 2 : CMD pm2-docker --json start ./pm2.json
 ---> Running in 2c3179e30171
 ---> 193f478715cb
Removing intermediate container 2c3179e30171
Successfully built 193f478715cb

$ docker run your-app-name .

container_linux.go:247: starting container process caused "exec: \".\": executable file not found in $PATH"
docker: Error response from daemon: containerd: container not started.
```

**Comment by simonepri** [comment]
Let's assume that the folder where you are building the image contains

> Dockerfile
> package.json
> pm2.json
> src           #folder with your source code

```
FROM keymetrics/pm2-docker-alpine:latest

# Bundle APP files
COPY src src/
COPY package.json .
COPY pm2.json .


# Install app dependencies
ENV NPM_CONFIG_LOGLEVEL warn
RUN npm install --production

# Show current folder structure in logs
RUN ls -al -R

# Start the server
CMD [ "pm2-docker", "start", "pm2.json" ]
```

Let me know if it works.

**Comment by simonepri** [comment]
I got it, the sintax in the guide was wrong:
![image](https://user-images.githubusercontent.com/3505087/28304933-167c6d84-6b9a-11e7-9008-cd9344468a12.png)
You should place the --json option after the start command.

**Comment by axetroy** [comment]
@simonepri 
> You should place the --json option after the start command.

It did't work. throw an same error as before.

```bash
container_linux.go:247: starting container process caused "exec: \".\": executable file not found in $PATH"
docker: Error response from daemon: containerd: container not started.
```

> Let's assume that the folder where you are building the image contains

I am writing in Typescript and compile to ES6.

here is my project dir:

- [x] package.json
- [x] pm2.json
- [x] Dockerfile
- [x] app (Source code write in Typescript, not for production)
- [x] build (Output code, deploy in production)

and I try to edit the Dockerfile like you given:
```Dockerfile
FROM keymetrics/pm2-docker-alpine:latest

# Bundle APP files
COPY build build/
COPY package.json .
COPY pm2.json .

# Install app dependencies
ENV NPM_CONFIG_LOGLEVEL warn
RUN npm install --production

# Show current folder structure in logs
RUN ls -al -R

# Start the server
CMD [ "pm2-docker", "start", "pm2.json" ]
```
Rebuild the Image and re-run container.

Noting change except print the file :(

**Comment by simonepri** [comment]
That's weird. Witch version of docker are you using?
Could you show us the `pm2.json` ?

I'll try on my side asap. Sorry for the problem 😞

**Comment by axetroy** [comment]
@simonepri 
```bash
$ docker --version
Docker version 1.12.6, build 78d1802
```

**pm2.json**
```json
{
  "apps": [{
    "name": "your-app-name",
    "script": "build/server.js",
    "env": {
      "production": false
    }
  }]
}
```

Thanks for your time. 👍

**Comment by simonepri** [comment]
It should be just
`docker run your-app-name`

Instead of 
`docker run your-app-name .`

My fault. Let me know about it.

**Comment by simonepri** [comment]
We have improved it even better: https://github.com/keymetrics/docker-pm2/commit/0c1bc4d317db0b69079286d8ef43e371e18a82a4

I'm closing it, feel free to reopen if you still have problems 👍

**Comment by axetroy** [comment]
@simonepri Already resolve, Thanks! :+1:
