### ISSUE TITLE
License in README.md is inconsistent with LICENSE file

### ISSUE THREAD

**Issue by edwinbs** [keymetrics/docker-pm2#32]
The License section in **README.md** says:

> This project is licensed under the GPL-3.0 License - see the LICENSE file for details.

While the **LICENSE** file is copy of the _MIT license_, which seems to be the intended license as it is newer in the commit history.

Please update the readme or license file to be consistent, because some organizations have restrictions against using GPL software.

**Comment by simonepri** [comment]
Solved with https://github.com/keymetrics/docker-pm2/commit/eaf622c47245a3d3700df05de777e9f4f2cf7446
Thank you for taking the time to open this issue. 🎉
