### ISSUE TITLE
Why there is exposed ports?

### ISSUE THREAD

**Issue by Shadowman4205** [keymetrics/docker-pm2#35]
My app run on port 5000

but with pm2, i see this
```
  "ExposedPorts": {
                "5000/tcp": {},
                "43554/tcp": {},
                "443/tcp": {},
                "80/tcp": {}
            },
```

Why this happening? Why these ports exposed?

**Comment by simonepri** [comment]
43554, 443,80 are exposed to let you use [keymetrics.io](https://keymetrics.io/)
@Unitech Am I wrong?

**Comment by Shadowman4205** [comment]
Yes u are right, i can see it  (http://docs.keymetrics.io/docs/pages/faq-troubleshooting/)[here]
