### ISSUE TITLE
TypeError: Cannot read property 'pm2_env' of undefined

### ISSUE THREAD

**Issue by nooballday** [keymetrics/docker-pm2#44]
I haven't been able to get docker-pm2 running because this particular error, 

i am using Hapijs as framework
this is my pm2.json

```js
{
  "apps": [{
    "name": "dockered-node",
    "script": "server.js",
    "env": {
      "production": true
    }
  }]
}
```

and this my Dockerfile

```
FROM keymetrics/pm2:latest
COPY package.json .
COPY pm2.json .
ENV NPM_CONFIG_LOGLEVEL warn
RUN npm install --production
RUN ls -al -R
CMD [ "pm2-docker", "start", "pm2.json" ]
EXPOSE 8000
```

TypeError: Cannot read property 'pm2_env' of undefined
    at /usr/local/lib/node_modules/pm2/lib/binaries/Runtime4Docker.js:94:26
    at /usr/local/lib/node_modules/pm2/lib/API.js:1009:21
    at /usr/local/lib/node_modules/pm2/lib/API.js:1080:19
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
    at replenish (/usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:993:25)
    at iterateeCallback (/usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:98
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:958:16
    at /usr/local/lib/node_modules/pm2/lib/API.js:1046:16
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:3096:16
    at replenish (/usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:998:17)

**Comment by SeanChristopherConway** [comment]
I am getting this same issue. Have you been able to resolve it?

**Comment by simonepri** [comment]
See these:
https://github.com/Unitech/pm2/issues/2870
https://github.com/Unitech/pm2/issues/2154
https://github.com/Unitech/pm2/issues/2908

Is mostly a problem on your side.

Feel free to reopen the issue with more details if you still have the problem.
