### ISSUE TITLE
Dockerfile does not build

### ISSUE THREAD

**Issue by andrewb-ms** [keymetrics/docker-pm2#54]
$ sudo docker build .
Sending build context to Docker daemon 11.78 kB
Step 1/8 : FROM keymetrics/pm2:{{tag}}
Error parsing reference: "keymetrics/pm2:{{tag}}" is not a valid repository/tag: invalid reference format

**Comment by simonepri** [comment]
`keymetrics/pm2:{{tag}}`
what is {{tag}} exactly?

**Comment by andrewb-ms** [comment]
It appears to be in the Dockerfile in this repo

**Comment by simonepri** [comment]
The `Dockerfile` inside `example-app` is not supposed to be used.
Please read the [Usage](https://github.com/keymetrics/docker-pm2#usage) section.

**Comment by simonepri** [comment]
Feel free to re-open if necessary!
