### ISSUE TITLE
Node.js v10 support?

### ISSUE THREAD

**Issue by inspiredjw** [keymetrics/docker-pm2#58]
Node.js v10 is out for a while.

10-* tags are needed to be created.

**Comment by iamsimakov** [comment]
hi guys, I think it is not actual now, the latest version available:

`$ docker run -it keymetrics/pm2:latest-stretch node -v`

v10.7.0

thanks for creators)

**Comment by simonepri** [comment]
Sorry for the delay, they are now online!
