### ISSUE TITLE
Update images

### ISSUE THREAD

**Issue by marcneander** [keymetrics/docker-pm2#62]
Node 10.13 LTS is out. Let's go!

**Comment by simonepri** [comment]
![image](https://user-images.githubusercontent.com/3505087/48978690-b61b8500-f0af-11e8-9361-f82ca923f114.png)
@Unitech for some reason the builds are not triggered automatically anymore.
I checked the configuration, and they look good.
Any idea?
In the meanwhile, I've triggered the build manually.

**Comment by ryanguill** [comment]
I am also seeing that the images are still not up to date, is there something we can do to get the latest images for now and see what is causing them not to build automatically.  Happy to help myself if I can.

**Comment by simonepri** [comment]
@vmarchaud @Unitech 
Any idea?

**Comment by simonepri** [comment]
@ryanguill The images seems to be updated to me.
What's wrong?

**Comment by ryanguill** [comment]
I apologize, I had apparently used an earlier version of 10-jessie and it didnt pull the latest version this morning. Sorry for the noise.
