### ISSUE TITLE
Docker image: keymetrics/pm2:latest-alpine stopped working.

### ISSUE THREAD

**Issue by shako92** [keymetrics/docker-pm2#63]
I see an update on 10th of December(today) on your Docker Hub at around 09:00 AM with ET.
And after this update containers based on your image stopped working.

When containers try to start I see such error:
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module './add_days/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/date-fns/index.js:2:12)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)

**Comment by shako92** [comment]
![image](https://user-images.githubusercontent.com/2061153/49741503-8ef2b500-fc64-11e8-97d0-a32bcd7ac6d2.png)
All tags were updated at the same time in your docker hub.

**Comment by leon-wu** [comment]
+1 it seems date-fns 1.30.1 new release is the cause.

**Comment by Unitech** [comment]
are you still seing this exception? I've seen it once on travis but once we relaunched the test suite the issue is not thrown anymore

**Comment by leon-wu** [comment]
> are you still seing this exception? I've seen it once on travis but once we relaunched the test suite the issue is not thrown anymore

yes, still an issue with pm2:8-alpine

**Comment by hamon-e** [comment]
same issue for me with pm2:8-alpine

**Comment by hamon-e** [comment]
if i build the Dockerfile locally I don't have any issue although, can you re run the build ?

**Comment by shako92** [comment]
I still see issue when building locally:
<img width="769" alt="image" src="https://user-images.githubusercontent.com/2061153/49748452-ad13e180-fc73-11e8-87f1-3964e8b4ff40.png">

**Comment by shako92** [comment]
> are you still seing this exception? I've seen it once on travis but once we relaunched the test suite the issue is not thrown anymore

Yes issue is still there

**Comment by Unitech** [comment]
I re ran the build, are you still noticing this error?

**Comment by shako92** [comment]
> I re ran the build, are you still noticing this error?

Yep now it works fine:
<img width="668" alt="image" src="https://user-images.githubusercontent.com/2061153/49753221-b5bee480-fc80-11e8-802e-9e766c8bb941.png">
