### ISSUE TITLE
keymetrics/pm2:12-alpine is missing from Docker Registry

### ISSUE THREAD

**Issue by anguspiv** [keymetrics/docker-pm2#75]
There is keymetrics/pm2:latest-alpine which is now pointing to Node 13.

But looking at the available (tags)[https://hub.docker.com/r/keymetrics/pm2/tags] to pull from, keymetrics/pm2:12-alpine is missing from the available tags.

Since we are on node 12, we cannot downgrade our pm2 tag, and node v13 breaks our docker build, preventing us from being able to build for production

**Comment by Unitech** [comment]
Waiting for inputs from @simonepri

**Comment by Unitech** [comment]
Repo reconfigured, 12-x image are incoming
