### ISSUE TITLE
Node v6 image is being shipped with unsupported pm2 version

### ISSUE THREAD

**Issue by thiren** [keymetrics/docker-pm2#76]
The latest node v6 image ships with a version of pm2 that no longer supports node v6. Apps fail to start if I try using this image. The problem is that the latest version of pm2 is always being installed when the image is built instead of a node v6 compatible version.

https://hub.docker.com/layers/keymetrics/pm2/6-alpine/images/sha256-fe5adedd68a040154db0689357b5abda3b28cd5851a9b8b620045af487f207a7

**Comment by Unitech** [comment]
https://github.com/keymetrics/docker-pm2/commit/f4af754d946b6f811a468d3d2741c3848f1964ef
