### ISSUE TITLE
Failed in cluster mode：/bin/busybox SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by xiezhuangping** [keymetrics/docker-pm2#82]
error log：
```
3|test | /bin/busybox:1
3|test |ELF
3|test | ^
3|test |
3|test | SyntaxError: Invalid or unexpected token
3|test |     at wrapSafe (internal/modules/cjs/loader.js:1063:16)
3|test |     at Module._compile (internal/modules/cjs/loader.js:1111:27)
3|test |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
3|test |     at Module.load (internal/modules/cjs/loader.js:996:32)
3|test |     at Function.Module._load (internal/modules/cjs/loader.js:896:14)
3|test |     at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:301:25
3|test |     at wrapper (/usr/local/lib/node_modules/pm2/node_modules/async/internal/once.js:12:16)
3|test |     at next (/usr/local/lib/node_modules/pm2/node_modules/async/waterfall.js:96:20)
3|test |     at /usr/local/lib/node_modules/pm2/node_modules/async/internal/onlyOnce.js:12:16
3|test |     at WriteStream.<anonymous> (/usr/local/lib/node_modules/pm2/lib/Utility.js:186:13)
```

Dockfile
```
FROM  keymetrics/pm2:latest-alpine
ENV ENV=online
ENV HOST 0.0.0.0

WORKDIR /usr/src/app
COPY . .

ENV NPM_CONFIG_LOGLEVEL warn

RUN npm install && npm run build

EXPOSE 3000
CMD [ "pm2-runtime", "start", "ecosystem.config.js" ]
```

ecosystem.config.js：
```
module.exports = {
  apps : [{
    name: 'test',
    script: './node_modules/.bin/nuxt start',
    instances: 4,
    exec_mode: 'cluster',
    autorestart: true,
    watch: true,
    watch_delay: 1000,
    ignore_watch : [".nuxt", ".editorconfig", "node_modules", "static"],
    max_memory_restart: '4G',
    env: {
      ENV: 'online'
    }
  }]
};
```

It‘s OK in fork mode.

**Comment by vladislav-mikheev** [comment]
found a solution?

**Comment by xiezhuangping** [comment]
> found a solution?

yes, here is my ecosystem.config.js:

// https://github.com/JkmAS/nuxt-pm2-cluster
// https://github.com/nuxt/nuxt.js/issues/3778
// https://github.com/nuxt/nuxt.js/issues/2630
// https://github.com/Unitech/pm2/issues/4082
// https://www.npmjs.com/package/nuxt-start
// https://github.com/nuxt/nuxt.js
module.exports = {
  apps: [
    {
      name: 'test',
      script: './node_modules/nuxt-start/bin/nuxt-start.js',
      cwd: './',
      args: `-c '/usr/src/app/nuxt.config.js'`,
      instances: 4,
      exec_mode: 'cluster',
      autorestart: true,
      watch: ['.nuxt', 'nuxt.config.js'],
      watch_delay: 1000,
      ignore_watch: ['node_modules', 'static'],
      watch_options: {
        'followSymlinks': false,
        'usePolling': true,
      },
      max_memory_restart: '4G',
      env: {
        ENV: 'online'
      },
    },
  ],
}

**Comment by xiezhuangping** [comment]
> found a solution?

yes, here is my ecosystem.config.js:
`
// https://github.com/nuxt/nuxt.js/issues/3778
// https://github.com/nuxt/nuxt.js/issues/2630
// https://github.com/JkmAS/nuxt-pm2-cluster
// https://github.com/Unitech/pm2/issues/4082
// https://www.npmjs.com/package/nuxt-start
// https://github.com/nuxt/nuxt.js
module.exports = {
  apps: [
    {
      name: 'test',
      script: './node_modules/nuxt-start/bin/nuxt-start.js',
      cwd: './',
      args: `-c '/usr/src/app/nuxt.config.js'`,
      instances: 4,
      exec_mode: 'cluster',
      autorestart: true,
      watch: ['.nuxt', 'nuxt.config.js'],
      watch_delay: 1000,
      ignore_watch: ['node_modules', 'static'],
      watch_options: {
        'followSymlinks': false,
        'usePolling': true,
      },
      max_memory_restart: '4G',
      env: {
        ENV: 'online'
      },
    },
  ],
}
`

**Comment by xiezhuangping** [comment]
> found a solution?

yes, here is my ecosystem.config.js:

```
// https://github.com/nuxt/nuxt.js/issues/3778
// https://github.com/nuxt/nuxt.js/issues/2630
// https://github.com/JkmAS/nuxt-pm2-cluster
// https://github.com/Unitech/pm2/issues/4082
// https://www.npmjs.com/package/nuxt-start
// https://github.com/nuxt/nuxt.js
module.exports = {
  apps: [
    {
      name: 'test',
      script: './node_modules/nuxt-start/bin/nuxt-start.js',
      cwd: './',
      args: `-c '/usr/src/app/nuxt.config.js'`,
      instances: 4,
      exec_mode: 'cluster',
      autorestart: true,
      watch: ['.nuxt', 'nuxt.config.js'],
      watch_delay: 1000,
      ignore_watch: ['node_modules', 'static'],
      watch_options: {
        'followSymlinks': false,
        'usePolling': true,
      },
      max_memory_restart: '4G',
      env: {
        ENV: 'online'
      },
    },
  ],
}
```

**Comment by xiezhuangping** [comment]
> found a solution?

btw, you need to run 'npm install nuxt-start' first
