### ISSUE TITLE
[12] [alpine] [slim] outdated images

### ISSUE THREAD

**Issue by josefschabasser** [keymetrics/docker-pm2#85]
Hi!

The images on docker hub are outdated.
Current Node 12 LTS version is 12.18.3, the images provide 12.16.2.

```
$ docker run keymetrics/pm2:12-slim node --version
v12.16.2

$ docker run node:12-slim node --version
v12.18.3
```

Best regards
Josef

EDIT: Maybe other images are outdated as well.

**Comment by Unitech** [comment]
updated
